### ISSUE TITLE
Questionable IRIs

### ISSUE THREAD

**Issue by ccondit** [monarch-initiative/GENO-ontology#12]
There are a few IRIs in geno.owl that use invalid URIs:

``` xml
<!-- http://urigen-plugin/ontology-iri -->
    <owl:AnnotationProperty rdf:about="http://urigen-plugin/ontology-iri">
        <rdfs:label xml:lang="en">ontology-iri</rdfs:label>
    </owl:AnnotationProperty>

    <!-- http://urigen-plugin/server-url -->
    <owl:AnnotationProperty rdf:about="http://urigen-plugin/server-url">
        <rdfs:label xml:lang="en">server-url</rdfs:label>
    </owl:AnnotationProperty>
```

and

``` xml
<!-- http://property/refactor-include -->
    <owl:AnnotationProperty rdf:about="http://property/refactor-include"/>

<!-- http://property/refactor-include-subs -->
    <owl:AnnotationProperty rdf:about="http://property/refactor-include-subs"/>
```

Is this intentional? Should these be resolvable IRIs?

/cc @nlwashington

**Comment by mbrush** [comment]
These IRIs were added to support some tooling that I Shahim and I are developing, which reads these property IRIs to support module extraction or URI creation scripts.  They are not part of GENO proper, and should not have been in geno.owl in the first place. Apologies . . . going forward I will keep such properties segregated in a separate owl file that is not in the import chain. 

Generally, GENO needs some major refactoring to clean up outdated and experimental features, and align with some recent modeling decisions and developments.  I hope to get to this in the next month or so.  Note that all IRIs used in the Monarch data should remain valid, but there will be major changes to the ontology structure. Just a heads up in case there are any dependencies on your end.
