### ISSUE TITLE
karyotype

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/GENO-ontology#16]
add karyotypes as a kind of (or is a part of) genotype?
there are also probably subtypes, like:

<pre>
[Karyotype](http://en.wikipedia.org/wiki/Karyotype)
  Visible Karyotype  (such as by FISH)
  [Virtual Karyotype](http://en.wikipedia.org/wiki/Virtual_karyotype)
    Array-based karyotype 
          SNP array karyotype
          arrayCGH karyotype
    Sequencing-based karyotype
</pre>

some issues:
*not sure you want to include methods (arrayCGH, etc) in the classes here (maybe too granular)?  but these do convey some level of resolution that might otherwise be missed.
*sequence-based karyotype is kind-of a new technique.  i found only this related patent here:
http://www.google.com/patents/US20050221341

for examples, we get karyotypes from Coriell. being able to represent these in our model will be hugely important for cancer use cases.  for example, "get all cell lines where karyotype information is available".

somewhat related to https://github.com/monarch-initiative/GENO-ontology/issues/11

**Comment by nlwashington** [comment]
the only term that i could find, but not what we need:
http://www.ebi.ac.uk/efo/EFO_0004426

**Comment by selewis** [comment]
I can see the need to add karyotype, but can logically see it as either a
'kind of' or a 'part of' a genotype. While the banding pattern (that is, a
karyotype) can reflect major chromosomal rearrangements, it's a far stretch
I think.

On Mon, Apr 13, 2015 at 3:30 PM, Nicole Washington <notifications@github.com

**Comment by jmcmurry** [comment]
Adding karyotype and chromosome are two possible ways to get out of dead end genotype pages; see https://github.com/monarch-initiative/monarch-app/issues/1319
