### ISSUE TITLE
haplotype

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/GENO-ontology#23]
We need to add the concept of haplotypes.  

Def from the interwebs:
A haplotype is a set of DNA variations, or polymorphisms, that tend to be inherited together. A haplotype can refer to a combination of alleles or to a set of single nucleotide polymorphisms (SNPs) found on the same chromosome.

clearly related, but not equivalent, to variant single locus complement.

required to properly express clinvar variants, and other data sources.

**Comment by kshefchek** [comment]
+1 or make SO:0001024 ! haplotype a subclass of genotype.

**Comment by mbrush** [comment]
added haplotype  class with commit e2836d6
