### ISSUE TITLE
Typo in the human taxon name 

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/GENO-ontology#24]
https://github.com/monarch-initiative/GENO-ontology/blob/develop/src/ontology/geno.owl#L5342

It should be a capital "H".

See https://github.com/monarch-initiative/monarch-app/issues/1224

**Comment by jnguyenx** [comment]
cc @cmungall @balhoff

**Comment by cmungall** [comment]
Other species too

**Comment by mbrush** [comment]
Updated labels in GENO.  If this is the source of the issue it should be resolved.
