### ISSUE TITLE
Add slides or link to slides in this repo

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/GENO-ontology#26]
We have good slides in our dropbox, We should either put them on slideshare or git add them here

**Comment by mbrush** [comment]
Will do.  Have soem content in the wiki, and a GENO paper and slide deck in the /docs folder of the repo, but they are a bit dated.  Will find most appropriate slides from Dropbox and add to repo.

**Comment by mbrush** [comment]
Updated the slide deck hosted in the github repo (docs folder), and added link to it from the README file.
