### ISSUE TITLE
geno0000846

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/GENO-ontology#28]
https://github.com/monarch-initiative/GENO-ontology/blob/develop/src/ontology/geno.owl#L144

missing underscore after geno

**Comment by TomConlin** [comment]
https://github.com/monarch-initiative/GENO-ontology/blob/develop/src/ontology/geno.owl#L154

geno0000846 too

**Comment by mbrush** [comment]
fixed.  thanks tom.
