### ISSUE TITLE
Integration issues with SciGraph

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/GENO-ontology#36]
(Not sure if this ticket belongs here or in SciGraph, but putting here for now)

When using the latest version of GENO we lose most of the genotype neo4j labels on our genotype nodes.
#### Genotypes
[Production Query](https://scigraph-data.monarchinitiative.org/scigraph/cypher/execute.json?cypherQuery=MATCH+%28n%3Agenotype%29+RETURN+COUNT%28DISTINCT%28n%29%29+as+genotypes)

[Dev Query](https://scigraph-data-dev.monarchinitiative.org/scigraph/cypher/execute.json?cypherQuery=MATCH+%28n%3Agenotype%29+RETURN+COUNT%28DISTINCT%28n%29%29+as+genotypes)

| field | count |
|-|-|
| genotypes | 44892 (-_656827_) 

This is resolved by using an older version of GENO - https://raw.githubusercontent.com/monarch-initiative/GENO-ontology/ce4caf5978824c25ffa15e0b0460369661e7ad4c/src/ontology/geno.owl

Our mapping to the genotype neo4j label is GENO:0000536.

**Comment by mbrush** [comment]
I've been doing some refactoring of GENO but don't think I've obsoleted any of the classes using to map SciGraph categories.  I checked the following mappings from the monarch load config file [here](https://github.com/monarch-initiative/SciGraph-docker-monarch-data/blob/master/src/main/resources/monarchLoadConfiguration.yaml.tmpl#L66) and the GENO classes used for category mappings are all still accounted for in the ontology:

- http://purl.obolibrary.org/obo/GENO_0000536 : genotype
- http://purl.obolibrary.org/obo/GENO_0000504 : reagent targeted gene
- #http://purl.obolibrary.org/obo/GENO_0000000 : intrinsic genotype
- #http://purl.obolibrary.org/obo/GENO_0000524 : extrinsic genotype
- #http://purl.obolibrary.org/obo/GENO_0000525 : effective genotype
- http://purl.obolibrary.org/obo/GENO_0000002 : variant locus
- http://purl.obolibrary.org/obo/GENO_0000871 : haplotype

@kshefchek Anything you can think of that I may have changed in GENO that would have caused this issue?  Can we get more specific info about the objects on which category labels have disappeared?  Is it a certain subset of objects mapped to GENO:0000536 ! genotype (e.g. a particular subtype such as effective genotypes? Or  objects all coming from a particular data source)?

**Comment by kshefchek** [comment]
I'm rebuilding scigraph with the latest version of GENO now, then I should be able to get more info for you.  I'll check each of those classes to see if anything looks off.

**Comment by kshefchek** [comment]
It looks like we are missing subClassOf relationships to extrinsic, intrinsic, and effective genotypes, see

https://scigraph-data-dev.monarchinitiative.org/scigraph/graph/neighbors.png?id=GENO:0000536&depth=10&relationshipType=subClassOf&direction=INCOMING

compared to

https://scigraph-data.monarchinitiative.org/scigraph/graph/neighbors.png?id=GENO:0000536&depth=10&relationshipType=subClassOf&direction=INCOMING

**Comment by mbrush** [comment]
It looks like all the subclass relationships in the first diagram are present in the second.  The second one just has additional nodes and subclass edges under GENO:0000719 (intrinsic genotype).  

The second diagram is definitely outdated - doesn't match the current GENO ontology.  

The first diagram matches the current ontology, but I cant see what  is under each of the second tier nodes to see if it is truly the current version.  My latest refactor of GENO made some changes in the hierarchy under GENO:0000719 (intrinsic genotype).

Also, want to make sure you know that the current/active version of GENO is in the 'develop' branch.  This has always been the case - just want to make sure that you are still using this version and not the one in master (which is 3 years old).

**Comment by kshefchek** [comment]
Each query is looking at all subclass paths starting at GENO:0000536 and looking at incoming edges, to a maximum depth of 10 edges.  Is it possible these subclassof axioms are missing in the latest ontology or could it be a scigraph integration bug.  We use the develop branch.

**Comment by mbrush** [comment]
All of  the classes in the second diagram are still present in the current GENO version.  the hierarchical structure under GENO:0000719 (intrinsic genotype) is just a bit different.  For example, an additional level of organizational nodes has been added directly under GENO:0000719 (intrinsic genotype).  Not sure if this would break things, or if this is a scigraph integration bug as you suggest.  Happy to show you the current structure in the ontology if that would help.

**Comment by kshefchek** [comment]
Taking a look at it in protege, I think the issue is that there is not an explicit subClassOf axiom between genomic genotype and intrinsic genotype, but this can be inferred when running elk over the ontology.  I'm guessing this is intended and the easiest solution is configuring scigraph to reason over the ontology with elk prior to importing into neo4j.  I'll update the configuration and see if that fixes it.

**Comment by kshefchek** [comment]
This is fixed with adding elk.
