### ISSUE TITLE
Alternative label on http://www.geneontology.org/formats/oboInOwl#hasDbXref in geno.owl

### ISSUE THREAD

**Issue by dosumis** [monarch-initiative/GENO-ontology#40]
Geno sets the rdfs:label of http://www.geneontology.org/formats/oboInOwl#hasDbXref as hasDbXref when other sources have it as database_cross_reference. 

Ideally this should all be set centrally with imports.  In the absence of that, can geno.owl be changed to conform?

ontology_name | IRI | label | short_form
-- | -- | -- | --
vfb | http://www.geneontology.org/formats/oboInOwl#hasDbXref | database_cross_reference | hasDbXref
fbdv | http://www.geneontology.org/formats/oboInOwl#hasDbXref | database_cross_reference | hasDbXref
fbcv | http://www.geneontology.org/formats/oboInOwl#hasDbXref | database_cross_reference | hasDbXref
ro | http://www.geneontology.org/formats/oboInOwl#hasDbXref | database_cross_reference | hasDbXref
so | http://www.geneontology.org/formats/oboInOwl#hasDbXref | database_cross_reference | hasDbXref
geno | http://www.geneontology.org/formats/oboInOwl#hasDbXref | has_dbxref |
fbbi | http://www.geneontology.org/formats/oboInOwl#hasDbXref | database_cross_reference | hasDbXref

**Comment by mbrush** [comment]
Thanks David. Fixed manually for now.  Will set up automate import pipeline soon, to ensure all imported labels/terms are kept current.
