### ISSUE TITLE
Include OBO and JSON as released files

### ISSUE THREAD

**Issue by kltm** [monarch-initiative/GENO-ontology#42]
Currently, GENO apparently only includes OWL for release (OBOF page). To reach a wider audience (tagging AGR/Alliance's @sierra-moxon), it would be nice to have OBO and JSON available as well.

Use of ROBOT is the current workaround.

Tagging @cmungall

**Comment by matentzn** [comment]
Yes, we should install the latest ODK here as well. Matt, do you want to
set up a meet for late May to do this together?

**Comment by monicacecilia** [comment]
:ghost: _... I am the ghost of forgotten tickets._

Dear @mbrush .... did something ever happen here?

**Comment by matentzn** [comment]
Oh yes this was done! Forgot to close. See here: https://github.com/monarch-initiative/GENO-ontology you would be able to replace the .owl in the Geno PURL by .json and that would work!
