### ISSUE TITLE
Add textual definitions for zygosity terms.

### ISSUE THREAD

**Issue by mbrush** [monarch-initiative/GENO-ontology#63]
Most of the existing terms int he 'zygosity' hierarchy lack textual definitions.

**Comment by mbrush** [comment]
Stub below with some proposals:


**'disomic zygosity**' - a zygosity quality inhering in a single locus complement from a genome with a normal ploidy of two (i.e. with two copies of autosomal chromosomes).  Disomic zygosity concepts describe the degree of similarity of the two sequence features at a given autosomal locus (or the state of being the only feature at a given locus in the case of hemizygosity).

**'nullizygous'**:  a disomic zygosity quality inhering in a single locus complement comprised of two non-functional copies of a gene.  Loss of function may result from the gene being entirely missing via a deletion, or mutated in a way that eliminates its function.

**Comment by mbrush** [comment]
@ppavlidis I added 'nullizygous' to the ontology, and also added definitions to other zygosity terms where they were missing. 

Closing this issue but feel free to reopen if you think it requires more discussion.

**Comment by ppavlidis** [comment]
Thanks Matthew, quick question, when will this be available in geno.owl via the canonical purl?

**Comment by ppavlidis** [comment]
Oops, one more thing, reviewing the change: is it possible to add a synonym "Homozygous null" or something along those lines?

**Comment by mbrush** [comment]
Happy to add synonyms, but not sure 'homozygous null' is consistent with how I think of the notion of being 'nullizygous'  (which can cover cases where there are two _different_ null alleles at a given locus, such that it is not homozygous).

**Comment by ppavlidis** [comment]
> Happy to add synonyms, but not sure 'homozygous null' is consistent with how I think of the notion of being 'nullizygous' (which can cover cases where there are two _different_ null alleles at a given locus, such that it is not homozygous).

OK that's a useful distinction, but the term "homozygous null" gets used in the literature and my curators will be looking for it, so how about including it as a [narrow synonym](http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym) of the more general nullizygous concept. If you don't want to add another subclass for it.

**Comment by mbrush** [comment]
> how about including it as a [narrow synonym](http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym) of the more general nullizygous concept

Done

>  when will this be available in geno.owl via the canonical purl

Once the next release is cut, it will be available here.  and show up in resources like OLS and Ontobee.  I'll try to make this happen in the next week or so.
