### ISSUE TITLE
Implement github action to run a geno release

### ISSUE THREAD

**Issue by mbrush** [monarch-initiative/GENO-ontology#64]
As new content is added to geno-edit.owl to address community requests, we need a way to ensure that it propagates to the version of the ontology visible / useable to the community (e.g. in services/resources like OLs, Ontobee).  My understanding is that a release needs to be cut in order for these services to pick up new content.  

@matentzn suggested implementing a github action to allow for the release process to be initiated in a more automated way.

**Comment by matentzn** [comment]
@anitacaron would you be able to add this workflow here: https://github.com/pato-ontology/pato/blob/master/.github/workflows/build.yml

and see that it works?
